name: 功能建议
title: "[Feat] "
description: 加入或优化程序功能的提案
labels:
  - enhancement
assignees: IlyaYezelovsky
body:
  - type: checkboxes
    id: checkboxes-0
    attributes:
      label: 自检
      description: 在提交 Issue 前请自检以下内容
      options:
        - label: 我确认最新版本的 classutils 还没有此功能
        - label: 我确认我已搜索过 Issue 列表，发现此 Issue 没有被提交过
    validations:
      required: true
  - type: textarea
    id: textarea-1
    attributes:
      label: 功能描述
    validations:
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: 原因
    validations:
      required: true
  - type: textarea
    id: textarea-3
    attributes:
      label: 其他信息